baseURL = "http://enaverse.org/"
languageCode = "en-us"
title = "Enaverse"
theme = "minimal"

[params]
    author = "Matthew Lau"
    description = "Capture and analyze provenance to improve data science"
    githubUsername = "Enaverse"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Enaverse"
    weight = 1

[[menu.main]]
    url = "/FAQ/"
    name = "FAQs"
    weight = 7


[[menu.main]]
    url = "/communities/"
    name = "Communities"
    weight = 2

[[menu.main]]
    url = "/databases/"
    name = "Databases"
    weight = 3

[[menu.main]]
    url = "/models/"
    name = "Models"
    weight = 4


[[menu.main]]
    url = "/analyses/"
    name = "Analyses"
    weight = 5

[[menu.main]]
    url = "/goals/"
    name = "Goals"
    weight = 6


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:matthewklau@fas.harvard.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/enaverse/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/enaVerse/"
    name = "twitter"
    weight = 3
